# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb4c99b0c7dc1b23a01008f5c47020d260fdc3709abfce167d210ba9d59ddfaba31443923a7b30efea86a9c234d2bb292667eb3f6e0c3c9d63cff6620613fdc4

test:
  secret_key_base: 867ef8463993a26b8e18c0af1c466d0db2844875499685d3bc72bc294c45cad1ce0bbaa73b289aa51f05ed4032045ea9575629b28929f82d86b0d86f15071a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
